apiVersion: v2
name: cad-ml-platform
description: A Helm chart for CAD ML Platform
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/helm/icon/color/helm-icon-color.png
type: application
version: 0.1.0
appVersion: "1.6.0"
