{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cad-ml-platform.fullname" . }}-secret
  labels:
    {{- include "cad-ml-platform.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
